### ISSUE TITLE
velero pod 没有运行

### ISSUE THREAD

**Issue by morganwang010** [jibutech/helm-charts#122]
git clone到本地后，以本地helm仓库安装的方式，安装完成后，添加k8s集群一直处于连接状态，查看pod，velero 相关的Pod没有运行。问题大概在哪个地方？k8s集群版本1.26， 1.23都不行

**Comment by jerry-jibu** [comment]
@morganwang010 您这边安装的是哪个版本？可以从web界面上配置S3以后，再看下是否初始化完成；或者方便联系 support@jibudata.com 来看下具体情况不，基于描述可能是和环境相关的问题。
