### ISSUE TITLE
minikube k8s cluster install YS1000 issue

### ISSUE THREAD

**Issue by LLj-github-operations-develop** [jibutech/helm-charts#21]
![image](https://user-images.githubusercontent.com/55820450/145346337-d6914291-6b06-4621-9677-3b8b51550e68.png)

![image](https://user-images.githubusercontent.com/55820450/145346448-b41e8af6-7eec-4a9b-aace-c3a0fa700e64.png)

**Comment by jerry-jibu** [comment]
@LLj-github-operations-develop  what's your k8s version for installation?

**Comment by jerry-jibu** [comment]
@LLj-github-operations-develop we can't reproduce your issue on v1.22. Please feel free to reopen it if you still hit this issue. thanks.
