### ISSUE TITLE
Edit custom policy in YS1000 portal will show white screen

### ISSUE THREAD

**Issue by Biscuit024** [jibutech/helm-charts#74]
Create a custom backup policy without any problem. 
When I press the edit button to my custom policy it shows a white screen (not refresh, not redirect, just the whole page turns white screen), the browser backwards also does not work, just need to reload the page.
While the default policy is able to edit without showing a white screen.

Default policy:
![image](https://user-images.githubusercontent.com/14073611/184277982-fcab2b46-c75c-4c8c-a98c-287d723cdce5.png)

Custom policy:
![image](https://user-images.githubusercontent.com/14073611/184278050-938b99ce-ed52-48de-a20a-0e4522c0c530.png)

**Comment by jerry-jibu** [comment]
thanks @Biscuit024 , this should be a code bug. Which ys1000 version do you have? Would you mind to contact us through support@jibudata.com for more details? Thanks in advance.

**Comment by Biscuit024** [comment]
I was using v2.7, and I have updated to v2.8 yesterday, I saw this was fixed, many thanks. While I found another white screen bug when I try to create/edit migration plan, the white screen will happen when I go to copy options step.
![image](https://user-images.githubusercontent.com/14073611/188037468-b56a285d-3405-4c09-85e7-b973ae23bf97.png)
![image](https://user-images.githubusercontent.com/14073611/188037483-6e15b1ef-1d30-4750-ab82-87989b65dbd8.png)

**Comment by jerry-jibu** [comment]
close the stale issue, please feel free to reopen it when it can't be recreated, thanks,
